// Generated by .github/workflows/club-map.yml. Rows are added, never
// replaced - a row corrected by hand stays corrected.
//
// A manager's API-Football id, and the club he managed. Not a data
// source: it is a forwarding address.
//
// There is no free source for a manager anywhere. ESPN's roster names
// one and it is years out of date - it answered Arsene Wenger for
// Arsenal, who left in 2018 - so /coach/<n> stops existing when the
// paid plan does, on 23 September. What this saves is where those
// URLs land: the reader arrives at the club rather than at a 404.
//
// It could only be built while both the manager and his club were
// still visible in the same answer, which is to say before that date.
//
// Empty until the workflow has run once; the file exists so the code
// that reads it can ship without waiting for it.
export const TEAM_BY_COACH: Record<number, number> = {
};

export function clubOfCoach(coachId: number | null | undefined): number | null {
  if (typeof coachId !== "number") return null;
  return TEAM_BY_COACH[coachId] ?? null;
}
