export type ArticlePreview = {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  author: string;
  time: string;
  readTime: string;
  image: string;
  local?: boolean;
  featured?: boolean;
  basePath?: string;
};

export const categories = [
  { name: "Ֆուտբոլ", slug: "football" },
  { name: "Բասկետբոլ", slug: "basketball" },
  { name: "Թենիս", slug: "tennis" },
  { name: "Ֆորմուլա 1", slug: "formula-1" },
  { name: "MMA", slug: "mma" },
  { name: "Բռնցքամարտ", slug: "boxing" },
  { name: "Ծանրամարտ", slug: "weightlifting" },
  { name: "Ըմբշամարտ", slug: "wrestling" },
  { name: "Մարմնամարզություն", slug: "gymnastics" },
  { name: "Շախմատ", slug: "chess" },
  { name: "Այլ մարզաձևեր", slug: "other" },
];

export const demoArticles: ArticlePreview[] = [
  {
    slug: "armenia-team-new-cycle",
    category: "Ֆուտբոլ",
    title: "Հայաստանի հավաքականը նոր փուլ է սկսում․ ինչ է փոխվելու թիմում",
    excerpt: "Նոր մարզչական մոտեցում, երիտասարդ խաղացողներ և առաջիկա հանդիպումների հիմնական հարցերը՝ AIFootball-ի ամփոփմամբ։",
    author: "AIFootball խմբագրություն",
    time: "8 րոպե առաջ",
    readTime: "5 րոպե",
    image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1600&q=85",
    local: true,
    featured: true,
  },
  {
    slug: "champions-league-matchday",
    category: "Ֆուտբոլ",
    title: "Չեմպիոնների լիգայի երեկոն՝ գլխավոր հանդիպումներն ու սպասելիքները",
    excerpt: "Կազմերի նորություններ, մարզիչների որոշումներ և երեք առանցքային դիմակայություն։",
    author: "Արամ Սահակյան",
    time: "24 րոպե առաջ",
    readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "nba-night-review",
    category: "Բասկետբոլ",
    title: "NBA-ի գիշերը՝ ամենատպավորիչ ելույթներն ու վճռորոշ նետումները",
    excerpt: "Օրվա լավագույն խաղացողները և հանդիպումների արագ ամփոփումը։",
    author: "Դավիթ Գրիգորյան",
    time: "39 րոպե առաջ",
    readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "tennis-hard-court",
    category: "Թենիս",
    title: "Կոշտ ծածկույթի մրցաշարը մտնում է վճռորոշ փուլ",
    excerpt: "Ֆավորիտների ճանապարհը և օրվա ամենահետաքրքիր զույգերը։",
    author: "AIFootball խմբագրություն",
    time: "1 ժամ առաջ",
    readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "armenian-gymnastics-team-season",
    category: "Մարմնամարզություն",
    title: "Հայ մարմնամարզիկները պատրաստվում են մրցաշրջանի գլխավոր մեկնարկներին",
    excerpt: "Հավաքականի նախապատրաստական փուլը, նոր ծրագրերը և առաջիկա մրցաշարերի սպասելիքները։",
    author: "AIFootball խմբագրություն",
    time: "52 րոպե առաջ",
    readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1742249715229-0ce01dd19358?auto=format&fit=crop&w=1400&q=85",
    local: true,
  },
  {
    slug: "euroleague-round-preview",
    category: "Բասկետբոլ",
    title: "Եվրալիգայի տուրը՝ օրվա գլխավոր հանդիպումներն ու առանցքային զույգերը",
    excerpt: "Թիմերի մարզավիճակը, վնասվածքների վերջին տվյալներն ու սպասվող պայքարը։",
    author: "Դավիթ Գրիգորյան",
    time: "1 ժամ առաջ",
    readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "basketball-national-team-camp",
    category: "Բասկետբոլ",
    title: "Հայաստանի հավաքականը սկսել է նախապատրաստական հավաքը",
    excerpt: "Մարզչական շտաբը հրապարակել է հրավիրված խաղացողների ցանկն ու ծրագիրը։",
    author: "AIFootball խմբագրություն",
    time: "2 ժամ առաջ",
    readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?auto=format&fit=crop&w=1200&q=85",
    local: true,
  },
  {
    slug: "nba-transfer-market",
    category: "Բասկետբոլ",
    title: "NBA-ի տրանսֆերային շուկայի օրվա կարևոր զարգացումները",
    excerpt: "Նոր պայմանագրեր, փոխանակումների քննարկումներ և թիմերի ծրագրերը։",
    author: "Դավիթ Գրիգորյան",
    time: "3 ժամ առաջ",
    readTime: "5 րոպե",
    image: "https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "atp-ranking-update",
    category: "Թենիս",
    title: "ATP-ի վարկանիշային աղյուսակում նոր փոփոխություններ են գրանցվել",
    excerpt: "Առաջատարների դիրքերը և շաբաթվա ամենամեծ առաջընթացը գրանցած թենիսիստները։",
    author: "AIFootball խմբագրություն",
    time: "1 ժամ առաջ",
    readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1723980839948-95ccbffd3cb4?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "wta-semifinal-preview",
    category: "Թենիս",
    title: "WTA մրցաշարի կիսաեզրափակիչները խոստանում են լարված պայքար",
    excerpt: "Մրցակիցների ճանապարհը, վիճակագրությունն ու հաղթանակի գլխավոր գործոնները։",
    author: "Մարիամ Հարությունյան",
    time: "2 ժամ առաջ",
    readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "armenian-junior-tennis",
    category: "Թենիս",
    title: "Հայ պատանի թենիսիստները մեդալներով վերադարձել են մրցաշարից",
    excerpt: "Հայաստանի ներկայացուցիչների արդյունքներն ու եզրափակիչ հանդիպումների պատկերը։",
    author: "AIFootball խմբագրություն",
    time: "4 ժամ առաջ",
    readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1599586120429-48281b6f0ece?auto=format&fit=crop&w=1200&q=85",
    local: true,
  },
  {
    slug: "gymnastics-world-cup-medals",
    category: "Մարմնամարզություն",
    title: "Աշխարհի գավաթում հայ մարմնամարզիկները պայքարում են մեդալների համար",
    excerpt: "Որակավորման արդյունքները և եզրափակիչներում սպասվող ելույթները։",
    author: "AIFootball խմբագրություն",
    time: "1 ժամ առաջ",
    readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1743076851851-0762b336b56d?auto=format&fit=crop&w=1400&q=85",
    local: true,
  },
  {
    slug: "vault-final-analysis",
    category: "Մարմնամարզություն",
    title: "Զուգափայտի եզրափակիչը՝ բարդության գործակիցներն ու ֆավորիտները",
    excerpt: "Մասնակիցների վարժությունները և գնահատականների վրա ազդող կարևոր մանրամասները։",
    author: "Արամ Սահակյան",
    time: "2 ժամ առաջ",
    readTime: "5 րոպե",
    image: "https://images.unsplash.com/photo-1742249739458-7f49d1cec452?auto=format&fit=crop&w=1200&q=82",
  },
  {
    slug: "youth-gymnastics-championship",
    category: "Մարմնամարզություն",
    title: "Երևանում ավարտվել է մարմնամարզության պատանեկան առաջնությունը",
    excerpt: "Մրցանակակիրները, լավագույն վարժությունները և մասնագետների գնահատականները։",
    author: "AIFootball խմբագրություն",
    time: "3 ժամ առաջ",
    readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1772739649011-4e5e1c8b6b4d?auto=format&fit=crop&w=1200&q=82",
    local: true,
  },
  {
    slug: "armenian-boxer-next-fight",
    category: "Բռնցքամարտ",
    title: "Հայ բռնցքամարտիկի հաջորդ մենամարտի ամսաթիվը հայտնի է",
    excerpt: "Մրցակցի ուժեղ կողմերը, մարզական ճամբարը և սպասվող մարտավարությունը։",
    author: "Նարեկ Մարտիրոսյան",
    time: "1 ժամ առաջ",
    readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1200&q=85",
    local: true,
  },
  {
    slug: "yerevan-club-transfer",
    category: "Ֆուտբոլ",
    title: "Երևանյան ակումբը հայտարարել է նոր համալրման մասին",
    excerpt: "Ֆուտբոլիստի պայմանագրի ժամկետն ու գլխավոր մարզչի առաջին մեկնաբանությունը։",
    author: "AIFootball խմբագրություն",
    time: "2 ժամ առաջ",
    readTime: "2 րոպե",
    image: "https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=1200&q=85",
    local: true,
  },
  {
    slug: "chess-tournament-armenia",
    category: "Շախմատ",
    title: "Հայ գրոսմայստերները հաջող են մեկնարկել միջազգային մրցաշարում",
    excerpt: "Առաջին տուրերի արդյունքները և մրցաշարային իրավիճակը։",
    author: "Մարիամ Հարությունյան",
    time: "2 ժամ առաջ",
    readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=1200&q=85",
    local: true,
  },
  {
    slug: "european-football-transfers",
    category: "Ֆուտբոլ",
    title: "Եվրոպական տրանսֆերային շուկայի օրվա 7 կարևոր լուրերը",
    excerpt: "Պաշտոնական գործարքներ, բանակցություններ և հնարավոր տեղափոխություններ։",
    author: "Արամ Սահակյան",
    time: "3 ժամ առաջ",
    readTime: "6 րոպե",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "volleyball-national-team",
    category: "Այլ մարզաձևեր",
    title: "Վոլեյբոլի հավաքականը հրապարակել է ընդլայնված կազմը",
    excerpt: "Նոր անուններ և նախապատրաստական ծրագրի մանրամասները։",
    author: "AIFootball խմբագրություն",
    time: "4 ժամ առաջ",
    readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1592656094267-764a45160876?auto=format&fit=crop&w=1200&q=85",
    local: true,
  },
  {
    slug: "formula-one-weekend-preview",
    category: "Ֆորմուլա 1",
    title: "Ֆորմուլա 1-ի մրցափուլը՝ գլխավոր ինտրիգներն ու սպասվող պայքարը",
    excerpt: "Թիմերի թարմացումները, եղանակային պայմաններն ու շաբաթավերջի հիմնական հարցերը։",
    author: "AIFootball խմբագրություն", time: "18 րոպե առաջ", readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1400&q=85",
  },
  {
    slug: "formula-one-qualifying-focus",
    category: "Ֆորմուլա 1",
    title: "Որակավորման պայքարում ամեն վայրկյանը վճռորոշ է լինելու",
    excerpt: "Արագ շրջանի հավակնորդներն ու մեքենաների հավասարակշռության կարևորությունը։",
    author: "AIFootball խմբագրություն", time: "1 ժամ առաջ", readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "formula-one-team-strategy",
    category: "Ֆորմուլա 1",
    title: "Թիմերի ռազմավարությունը կարող է փոխել մրցավազքի ամբողջ պատկերը",
    excerpt: "Անվադողերի ընտրությունը, փիթ-ստոփերն ու անվտանգության մեքենայի գործոնը։",
    author: "AIFootball խմբագրություն", time: "2 ժամ առաջ", readTime: "5 րոպե",
    image: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "formula-one-driver-rivalry",
    category: "Ֆորմուլա 1",
    title: "Առաջատարների մրցակցությունը նոր փուլ է մտնում",
    excerpt: "Վարորդների ուժեղ կողմերն ու առաջիկա ուղեգծին հարմարվելու հնարավորությունները։",
    author: "AIFootball խմբագրություն", time: "3 ժամ առաջ", readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "mma-main-event-preview",
    category: "MMA",
    title: "MMA-ի գլխավոր մենամարտը՝ ոճերի բախում և վճռորոշ գործոններ",
    excerpt: "Մարտիկների մարզավիճակը, ուժեղ կողմերն ու հավանական մարտավարությունները։",
    author: "AIFootball խմբագրություն", time: "26 րոպե առաջ", readTime: "5 րոպե",
    image: "https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&w=1400&q=85",
  },
  {
    slug: "mma-armenian-fighters",
    category: "MMA",
    title: "Հայ մարտիկները պատրաստվում են առաջիկա մենամարտերին",
    excerpt: "Մարզական ճամբարների ընթացքն ու մրցակիցների մասին վերջին տվյալները։",
    author: "AIFootball խմբագրություն", time: "1 ժամ առաջ", readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?auto=format&fit=crop&w=1200&q=85", local: true,
  },
  {
    slug: "mma-weight-cut-guide",
    category: "MMA",
    title: "Քաշի կարգավորման վերջին փուլը և դրա ազդեցությունը մենամարտի վրա",
    excerpt: "Ինչպես են մարզիկները պահպանում ուժն ու վերականգնվում կշռումից հետո։",
    author: "AIFootball խմբագրություն", time: "2 ժամ առաջ", readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "mma-fight-analysis",
    category: "MMA",
    title: "Մենամարտի վերլուծություն․ ինչպես վերահսկել տարածությունն ու տեմպը",
    excerpt: "Հարվածային տեխնիկայի և գետնամարտի անցումների առանցքային դրվագները։",
    author: "AIFootball խմբագրություն", time: "3 ժամ առաջ", readTime: "6 րոպե",
    image: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "boxing-title-fight-preview",
    category: "Բռնցքամարտ",
    title: "Տիտղոսային մենամարտից առաջ հայտնի են դարձել վերջին մանրամասները",
    excerpt: "Բռնցքամարտիկների պատրաստվածությունը և ռինգում սպասվող մարտավարությունը։",
    author: "AIFootball խմբագրություն", time: "35 րոպե առաջ", readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?auto=format&fit=crop&w=1400&q=85",
  },
  {
    slug: "boxing-training-camp",
    category: "Բռնցքամարտ",
    title: "Մարզական ճամբարի վերջին շաբաթը՝ արագություն և դիմացկունություն",
    excerpt: "Մարզիչների շեշտադրումները և մենամարտից առաջ աշխատանքի վերջին փուլը։",
    author: "AIFootball խմբագրություն", time: "2 ժամ առաջ", readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "boxing-ranking-update",
    category: "Բռնցքամարտ",
    title: "Վարկանիշային աղյուսակում փոփոխվել են առաջատարների դիրքերը",
    excerpt: "Քաշային կարգերի գլխավոր տեղաշարժերն ու առաջիկա հավակնորդների պայքարը։",
    author: "AIFootball խմբագրություն", time: "4 ժամ առաջ", readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1583473848882-f9a5bc7fd2ee?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "weightlifting-team-preparation",
    category: "Ծանրամարտ",
    title: "Հայաստանի ծանրամարտի հավաքականը շարունակում է նախապատրաստությունը",
    excerpt: "Մարզիկների ծրագրերը և գլխավոր մրցաշարից առաջ մարզչական շտաբի աշխատանքը։",
    author: "AIFootball խմբագրություն", time: "42 րոպե առաջ", readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=85", local: true,
  },
  {
    slug: "weightlifting-technique-focus",
    category: "Ծանրամարտ",
    title: "Պոկում վարժությունում տեխնիկական մանրուքները որոշիչ են",
    excerpt: "Մեկնարկային դիրքը, ձողի արագությունն ու ամրագրման կարևորությունը։",
    author: "AIFootball խմբագրություն", time: "1 ժամ առաջ", readTime: "5 րոպե",
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "weightlifting-championship-preview",
    category: "Ծանրամարտ",
    title: "Առաջնության ֆավորիտներն ու սպասվող ծանր պայքարը",
    excerpt: "Քաշային կարգերի առաջատարներն ու մեդալային հավակնությունները։",
    author: "AIFootball խմբագրություն", time: "2 ժամ առաջ", readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "weightlifting-recovery",
    category: "Ծանրամարտ",
    title: "Վերականգնումը մրցաշարային պատրաստության կարևոր մասն է",
    excerpt: "Ծանրաբեռնվածության կառավարումը և մրցումից առաջ վերջին օրերի ծրագիրը։",
    author: "AIFootball խմբագրություն", time: "3 ժամ առաջ", readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "wrestling-national-team-camp",
    category: "Ըմբշամարտ",
    title: "Հայ ըմբիշները հավաք են անցկացնում կարևոր մեկնարկից առաջ",
    excerpt: "Մարզավիճակի գնահատումը, գոտեմարտային աշխատանքն ու կազմի ընտրությունը։",
    author: "AIFootball խմբագրություն", time: "30 րոպե առաջ", readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1400&q=85", local: true,
  },
  {
    slug: "wrestling-freestyle-preview",
    category: "Ըմբշամարտ",
    title: "Ազատ ոճի մրցաշարում սպասվում են մի քանի սկզբունքային գոտեմարտեր",
    excerpt: "Քաշային կարգերի գլխավոր զույգերն ու մրցակիցների ուժեղ կողմերը։",
    author: "AIFootball խմբագրություն", time: "1 ժամ առաջ", readTime: "4 րոպե",
    image: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "wrestling-greco-roman-technique",
    category: "Ըմբշամարտ",
    title: "Հունահռոմեական ոճում դիրքային պայքարը կրկին առանցքային է",
    excerpt: "Պաշտպանության, հակագրոհի և պարտերում աշխատանքի կարևոր դրվագները։",
    author: "AIFootball խմբագրություն", time: "2 ժամ առաջ", readTime: "5 րոպե",
    image: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=85",
  },
  {
    slug: "wrestling-young-talents",
    category: "Ըմբշամարտ",
    title: "Երիտասարդ ըմբիշները պայքարում են հավաքականի կազմում տեղ ունենալու համար",
    excerpt: "Նոր անուններ, մրցակցություն և մարզիչների գնահատականները։",
    author: "AIFootball խմբագրություն", time: "4 ժամ առաջ", readTime: "3 րոպե",
    image: "https://images.unsplash.com/photo-1583473848882-f9a5bc7fd2ee?auto=format&fit=crop&w=1200&q=85",
  },
];

export const trendingTopics = ["#ՀայաստանիՀավաքական", "#ՉեմպիոններիԼիգա", "#NBA", "#Տրանսֆերներ", "#Մենամարտ"];

export const liveMatches = [
  { status: "72′", competition: "Չեմպիոնների լիգա", home: "Բենֆիկա", away: "Ֆեներբահչե", homeScore: 1, awayScore: 1 },
  { status: "HT", competition: "Պրեմիեր լիգա", home: "Արսենալ", away: "Էվերթոն", homeScore: 2, awayScore: 0 },
  { status: "21:45", competition: "Սերիա Ա", home: "Միլան", away: "Ռոմա", homeScore: null, awayScore: null },
];

// No real opinion-piece content pipeline exists yet - left empty rather
// than filled with fake placeholder authors. The homepage section and
// /opinions page both hide themselves entirely when this is empty (same
// "no demo content" principle applied to demoArticles).
export const opinions: { author: string; role: string; title: string; initials: string }[] = [];
