// Generated by .github/workflows/club-map.yml. Rows are added, never
// replaced - a row corrected by hand stays corrected.
//
// The left number is API-Football's player id, which is what /player/<n>
// on this site runs on and what Google has indexed. The right one is
// ESPN's athlete id.
//
// Matched INSIDE one squad, never across a league. A family name is weak
// evidence among ten leagues of footballers and strong evidence among
// twenty-eight team-mates, and chooseAthlete still refuses the two who
// share one. A footballer who could not be told apart from a team-mate is
// absent, and his page renders exactly as it did before.
//
// Empty until the workflow has run once; the file exists so the code that
// reads it can ship without waiting for it.
export const ESPN_ATHLETE_BY_API_FOOTBALL: Record<number, string> = {
};

export function espnAthleteFor(apiFootballId: number | null | undefined): string | null {
  if (typeof apiFootballId !== "number") return null;
  return ESPN_ATHLETE_BY_API_FOOTBALL[apiFootballId] ?? null;
}
