// Generated by .github/workflows/club-map.yml. Rows are added, never
// replaced - a row corrected by hand stays corrected.
//
// The left number is API-Football's club id, which is what /team/<n> on
// this site runs on and what Google has indexed. The right one is ESPN's,
// which is where the squad, the roster and the crest come from once the
// paid plan ends on 23 September.
//
// Every row here was proved, not guessed: the two clubs' published squads
// share at least four surnames and no other club in the league shares as
// many. A club that could not show that is absent from this file, and its
// page keeps whatever lib/entity-cache.ts already holds rather than being
// pointed at somebody else. The rule is lib/club-match.ts.
export const ESPN_TEAM_BY_API_FOOTBALL: Record<number, string> = {
  33: "360",
  34: "361",
  35: "349",
  36: "370",
  40: "364",
  42: "359",
  45: "368",
  47: "367",
  49: "363",
  50: "382",
  51: "331",
  52: "384",
  55: "337",
  57: "373",
  63: "357",
  64: "306",
  65: "393",
  66: "362",
  746: "366",
  1346: "388",
};

export function espnTeamFor(apiFootballId: number | null | undefined): string | null {
  if (typeof apiFootballId !== "number") return null;
  return ESPN_TEAM_BY_API_FOOTBALL[apiFootballId] ?? null;
}
